[package]
name = "proxclmc"
version = "0.1.0"
edition = "2021"
authors = ["Florian Paul Azim Hoberg @gyptazy (gyptazy@gyptazy.com)"]
license = "GPL-3.0-or-later"

[dependencies]
ssh2 = { version = "0.9", features = ["vendored-openssl"] }